FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.25.4@sha256:e68f6a00e88586577fafa4d9cefad1349c2be70d21244321321c407474ff9bf2 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM moby/buildkit:v0.33.0-rootless@sha256:80b15f0735e87bab7bf59ec4d695dfb4a7cfb25521cf56dc75d6f256285b63ef

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-buildkit"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-buildkit"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-buildkit"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-buildkit"

COPY --from=build /src/dist/wp-buildkit /bin/wp-buildkit
ENTRYPOINT ["wp-buildkit"]
