FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.27.1@sha256:f44f6e88636cfb311f9ebace870ded69d943f227bb3cb27d32ffd84ea18c43ea AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM moby/buildkit:v0.26.1-rootless@sha256:d5456ed63f604b889ce1ccb7c178e929577f98e77e70ba7827cd8932d3c38fe8

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-buildkit"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-buildkit"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-buildkit"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-buildkit"

COPY --from=build /src/dist/wp-buildkit /bin/wp-buildkit
ENTRYPOINT ["wp-buildkit"]
