FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.25.3@sha256:6d4e5e74f47db00f7f24da5f53c1b4198ae46862a47395e30477365458347bf2 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM moby/buildkit:v0.23.2-rootless@sha256:cab936745de5d673465948f1e93ff4d6e372bbe33f218afd3314eba45a6f85a9

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-buildkit"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-buildkit"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-buildkit"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-buildkit"

COPY --from=build /src/dist/wp-buildkit /bin/wp-buildkit
ENTRYPOINT ["wp-buildkit"]
